name=input("Enter your name:")
lab=int(input("Enter your lab grade:"))
midterm=int(input("Enter your midterm grade:"))
final=int(input("Enter your final grade:"))
score=(lab*25/100)+(midterm*35/100)+(final*40/100)

print("Name:",name)
print("Lab:",lab)
print("Midterm:",midterm)
print("Final:",final)
print("Last Score:",score)